#!/usr/bin/env node
//
// Aggregates every verification marker in the repository into TODO-VERIFY.md.
//
// The accuracy rule in CONTENT-STYLE.md says that any number without a source
// or a measurement gets a marker instead of a guess. That rule only works if
// the markers are findable, and a hand-maintained index of them would be stale
// within a week. So the index is generated, and `make drift` fails when the
// committed file does not match what the sources say. The file in git is a
// build artifact that happens to be readable on GitHub.
//
//   node tools/collect-todos.mjs           write TODO-VERIFY.md
//   node tools/collect-todos.mjs --check    exit 1 if it is out of date

import { readFileSync, writeFileSync, readdirSync, statSync } from 'node:fs'
import { join, relative, extname } from 'node:path'
import { fileURLToPath } from 'node:url'

const ROOT = fileURLToPath(new URL('..', import.meta.url))
const OUT = join(ROOT, 'TODO-VERIFY.md')

const SCAN_DIRS = ['content', 'data', 'docs', 'firmware', 'hardware']
const SCAN_EXT = new Set(['.md', '.yaml', '.yml', '.json', '.py', '.c', '.h', '.ts', '.tsx'])
const SKIP_DIRS = new Set(['node_modules', '.git', '.next', 'out', '.vercel'])

// The three markers, in the order they appear in the report. Ordered by how
// close they are to being closeable: sourcing is desk work, hardware needs a
// board, photos need a finished board.
const KINDS = [
  {
    id: 'verify',
    pattern: 'TODO(verify)',
    heading: 'Needs a source or a measurement',
    blurb:
      'A number, price, link, or claim that is currently absent rather than guessed. ' +
      'Each entry states what evidence would close it.',
  },
  {
    id: 'confirm-on-hardware',
    pattern: 'TODO(confirm-on-hardware)',
    heading: 'Needs the physical hardware',
    blurb:
      'Procedures written out but not yet performed on a real board. These cannot close ' +
      'until hardware exists, and no page containing one may be marked verified.',
  },
  {
    id: 'confirm',
    pattern: 'TODO(confirm)',
    heading: 'Needs a decision',
    blurb: 'An open question awaiting a maintainer decision. See NOTES-FOR-WIL.md for context.',
  },
  {
    id: 'photo',
    pattern: 'TODO(photo)',
    heading: 'Needs a photograph',
    blurb: 'Image slots, each describing what the photograph must actually show.',
  },
]

function walk(dir, acc = []) {
  let entries
  try {
    entries = readdirSync(dir)
  } catch {
    return acc
  }
  for (const entry of entries) {
    if (SKIP_DIRS.has(entry)) continue
    const full = join(dir, entry)
    if (statSync(full).isDirectory()) walk(full, acc)
    else if (SCAN_EXT.has(extname(full))) acc.push(full)
  }
  return acc
}

// A marker's text runs from the marker to the end of its block. In YAML that is
// a folded scalar continuing until dedent or the next key; in Markdown it is
// the rest of the paragraph. One heuristic covers both: keep taking lines until
// a blank line, a new YAML key, a heading, or a list bullet.
function extractMarkers(text, file) {
  const lines = text.split('\n')
  const found = []

  for (let i = 0; i < lines.length; i++) {
    const kind = KINDS.find((k) => lines[i].includes(k.pattern))
    if (!kind) continue

    const lineNo = i + 1
    const parts = [lines[i].slice(lines[i].indexOf(kind.pattern) + kind.pattern.length)]
    for (let j = i + 1; j < lines.length; j++) {
      const next = lines[j]
      if (!next.trim()) break
      if (/^\s*#/.test(next)) break
      if (/^\s*-?\s*[A-Za-z_][\w-]*:\s/.test(next) || /^\s*-?\s*[A-Za-z_][\w-]*:$/.test(next)) break
      if (/^\s*[-*]\s/.test(next)) break
      if (/^#{1,6}\s/.test(next)) break
      if (KINDS.some((k) => next.includes(k.pattern))) break
      parts.push(next)
      i = j
    }

    const body = parts
      .join(' ')
      .replace(/^[:\s>]+/, '')
      .replace(/\s+/g, ' ')
      .replace(/["']$/, '')
      .trim()

    found.push({ kind: kind.id, file, lineNo, text: body })
  }
  return found
}

function collect() {
  const markers = []
  for (const dir of SCAN_DIRS) {
    for (const file of walk(join(ROOT, dir))) {
      const rel = relative(ROOT, file)
      markers.push(...extractMarkers(readFileSync(file, 'utf8'), rel))
    }
  }
  return markers
}

function render(markers) {
  const now = new Date().toISOString().slice(0, 10)
  const out = []

  out.push('# TODO-VERIFY')
  out.push('')
  out.push('<!-- Generated by tools/collect-todos.mjs. Do not edit by hand. -->')
  out.push('<!-- Regenerate with `make todos`. CI fails if this file is stale. -->')
  out.push('')
  out.push(
    'Every unverified claim in the repository, in one place. This file is the ' +
      'accuracy rule made visible: oApogee does not publish a number it has not ' +
      'measured or sourced, so anything missing is listed here rather than guessed at.'
  )
  out.push('')
  out.push(`Generated ${now}. ${markers.length} open markers.`)
  out.push('')

  out.push('| Kind | Count |')
  out.push('|---|---|')
  for (const kind of KINDS) {
    out.push(`| ${kind.pattern} | ${markers.filter((m) => m.kind === kind.id).length} |`)
  }
  out.push('')

  for (const kind of KINDS) {
    const mine = markers.filter((m) => m.kind === kind.id)
    if (!mine.length) continue
    out.push(`## ${kind.heading}`)
    out.push('')
    out.push(kind.blurb)
    out.push('')
    const byFile = new Map()
    for (const m of mine) {
      if (!byFile.has(m.file)) byFile.set(m.file, [])
      byFile.get(m.file).push(m)
    }
    for (const [file, entries] of [...byFile.entries()].sort()) {
      out.push(`### \`${file}\``)
      out.push('')
      for (const e of entries) {
        out.push(`- **L${e.lineNo ?? '?'}** ${e.text}`)
      }
      out.push('')
    }
  }

  return out.join('\n') + '\n'
}

// The generated date changes daily and would otherwise make every CI run fail
// the staleness check. Compare everything except that line.
function stripVolatile(s) {
  return s.replace(/^Generated \d{4}-\d{2}-\d{2}\./m, 'Generated <date>.')
}

const markers = collect()
const rendered = render(markers)

if (process.argv.includes('--check')) {
  let current = ''
  try {
    current = readFileSync(OUT, 'utf8')
  } catch {
    console.error('TODO-VERIFY.md is missing. Run `make todos`.')
    process.exit(1)
  }
  if (stripVolatile(current) !== stripVolatile(rendered)) {
    console.error('TODO-VERIFY.md is out of date. Run `make todos` and commit the result.')
    process.exit(1)
  }
  console.log(`TODO-VERIFY.md is current (${markers.length} markers).`)
} else {
  writeFileSync(OUT, rendered)
  console.log(`Wrote TODO-VERIFY.md with ${markers.length} markers.`)
}
