// GENERATED by tools/gen-mechanical.mjs from data/mechanical.yaml. Do not edit.
//
// Change a dimension in data/mechanical.yaml and run `make mech`. Editing this
// file directly means the site and the model disagree, and the site is what a
// builder reads before ordering.
//
// 8 of these 28 dimensions are provisional: not measured, not
// sourced, and they will change. They are marked PROVISIONAL below. A part
// printed from them is a fit-check, not a finished component.

// --------------------------------------------------------------------------
// BOARD
// The payload PCB. Nothing here is measured, because nothing has been
// fabricated. These are the constraints the board will be designed to meet
// rather than observations of one that exists.

// Long dimension of the PCB outline. [PROVISIONAL]
//   TODO(confirm-on-hardware): fix the board outline in the PCB layout, then
//   measure a fabricated board with calipers and replace this. Until then both
//   printed parts are sized for a rectangle that does not exist yet.
board_length = 55;  // mm

// Short dimension of the PCB outline. [PROVISIONAL]
//   TODO(confirm-on-hardware): as board_length. Bounded from above by the sled:
//   a BT-50 has a 24.1 mm bore, the sled needs a wall and a print clearance on
//   each side, and that leaves about 20 mm. The bound is real, the exact figure
//   is not; the layout decides it.
board_width = 20;  // mm

// PCB thickness. [standard]
//   The default thickness for two-layer FR-4 at every prototype fabricator, and
//   what the board will be ordered as. This one is safe to build against.
board_thickness = 1.6;  // mm

// Mounting hole diameter, M2 close clearance. [standard]
//   ISO 273 close-fit clearance hole for an M2 screw. The sled posts are sized
//   from this rather than the other way round.
mount_hole_dia = 2.2;  // mm

// Centre of each mounting hole, in from both board edges. [PROVISIONAL]
//   TODO(confirm-on-hardware): set by the PCB layout once the outline and the
//   keepouts around the USB connector and the antenna are fixed.
mount_hole_inset = 3;  // mm

// Tallest component above the board. [PROVISIONAL]
//   TODO(confirm-on-hardware): measure the assembled board. Likely set by the
//   USB-C receptacle or the buzzer, both of which are among the tallest parts in
//   the bill of materials.
comp_height_top = 4;  // mm

// Tallest component below the board. [PROVISIONAL]
//   TODO(confirm-on-hardware): measure the assembled board. Sets how far the
//   board stands off the sled floor, so a wrong value here means the board does
//   not sit flat.
comp_height_bottom = 1.5;  // mm

// --------------------------------------------------------------------------
// CELL
// The lithium pouch. Sized for the cell cavity to hold it without compression,
// because a pouch cell under sustained pressure is a hazard.

// Cell cavity length. [PROVISIONAL]
//   TODO(verify): the bill of materials does not name a specific cell yet, and
//   cannot until the current draw of each tier has been measured. These
//   dimensions are for a common 1S pouch in the 150 to 250 mAh range and will be
//   replaced with the dimensions of the cell actually chosen.
cell_length = 35;  // mm

// Cell cavity width. [PROVISIONAL]
//   TODO(verify), as cell_length.
cell_width = 20;  // mm

// Cell cavity depth. [PROVISIONAL]
//   TODO(verify), as cell_length. Includes the protection circuit, which sits at
//   one end of the pouch and is often thicker than the pouch itself.
cell_thickness = 6;  // mm

// Slack added around the cell on every face. [practice]
//   A pouch cell must not be a press fit. Cells swell slightly with age and
//   charge state, and a cavity that grips one is applying sustained pressure to
//   a lithium pouch. Retention is the strap's job, not the cavity's.
cell_squeeze = 0.6;  // mm

// --------------------------------------------------------------------------
// AIRFRAME
// The rocket the payload attaches to. These are the parameters a builder
// changes for their own vehicle, and the reason the source is published rather
// than only the STLs.

// Body tube outside diameter the pod saddle is cut for. [standard]
//   Estes BT-50, 0.976 in from the published catalogue dimension. This is the
//   one parameter most builders will change, which is the whole reason the
//   source is published. Measure your own tube: paper tube stock varies with
//   humidity and between production runs, and the saddle is the surface where
//   that variation shows up as a rock.
tube_od = 24.8;  // mm

// Body tube inside diameter the sled is sized for. [standard]
//   Estes BT-50, 0.950 in from the published catalogue dimension. As tube_od,
//   measure your own.
tube_id = 24.1;  // mm

// --------------------------------------------------------------------------
// POD
// The external fairing, Form B.

// Fairing wall thickness. [derived]
//   Four perimeters at a 0.4 mm nozzle. Chosen as a multiple of the extrusion
//   width so the slicer produces solid wall rather than a thin gap it has to
//   fill badly.
pod_wall = 1.6;  // mm

// Length of the tapered leading fairing. [practice]
//   A taper long enough to keep the flow attached, kept short because every
//   millimetre is mass and drag on the outside of somebody's rocket. The
//   altitude penalty this trades against is unmeasured, and the Mounting page
//   says so.
pod_nose_len = 18;  // mm

// Length of the tapered trailing fairing. [practice]
//   Longer than the nose. A blunt tail separates the flow and separation costs
//   far more drag than a blunt leading edge does.
pod_tail_len = 26;  // mm

// Width of each strap slot. [standard]
//   Clears 1/2 in hook-and-loop strap, the common size, and comfortably clears a
//   3.6 mm cable tie. Two slots, so the pod is held at both ends.
strap_slot_width = 13;  // mm

// Height of each strap slot. [practice]
//   Passes doubled hook-and-loop without forcing it.
strap_slot_height = 2.4;  // mm

// How far the body tube sinks into the underside of the pod. [practice]
//   Deep enough that the pod cannot rock on the tube, shallow enough that the
//   pod does not stand proud of it any further than it must. The saddle is cut
//   for tube_od, so changing the tube diameter reshapes this surface.
pod_saddle_depth = 4;  // mm

// Slack between the board and the cell inside the cavity. [practice]
//   Keeps the board off the pouch. Foam or tape fills it on assembly.
pod_cavity_gap = 1;  // mm

// Cavity length added at each end for the screw bosses. [practice]
//   The cap screws into two bosses standing inside the cavity, clear of the
//   board at both ends. This is the room they need.
pod_boss_pad = 5.5;  // mm

// How far the base wall continues up inside the cap. [practice]
//   A spigot, so the two halves locate on each other rather than on the two
//   screws. Screws through an unaligned joint bend the cap instead of closing
//   it.
pod_lip_height = 2.5;  // mm

// Number of static port pilot marks. [derived]
//   From the rule on the Mounting page: more than one, evenly spaced, to average
//   out yaw and roll. Four is the count that page recommends. The diameter is
//   deliberately not published here, and the pod prints dimples rather than
//   holes for that reason.
port_count = 4;

// --------------------------------------------------------------------------
// SLED
// The internal carrier, Form A.

// Height of the side rails that locate the sled in the tube. [practice]
//   Enough to keep the sled from rotating in the tube without turning it into a
//   piston that has to be forced in.
sled_rail_height = 3;  // mm

// Height of the end stops that keep the board from sliding out. [practice]
sled_end_stop = 4;  // mm

// --------------------------------------------------------------------------
// PRINTING
// Tuned for the machine, not for the design. Every one of these is worth
// changing if your first fit-check is tight or loose.

// Gap added to every sliding or mating surface. [practice]
//   A starting point for FDM, not a specification. If your first fit-check is
//   tight, raise it; a well-tuned machine may want less. This is the number to
//   change before blaming the model.
fit_clearance = 0.3;  // mm

// Nozzle diameter the wall thicknesses are multiples of. [practice]
nozzle = 0.4;  // mm

// Solid floor under the board and the cell. [derived]
//   Three layers at 0.4 mm. Enough to be stiff without adding mass.
floor_thickness = 1.2;  // mm

// --------------------------------------------------------------------------
// DELIBERATELY UNSET
// The Mounting page refuses to publish a static port diameter until it has been
// derived from the enclosed volume and confirmed by flying two configurations.
// A default here would make that refusal false in the one place a builder acts
// on it, so the pod prints dimpled pilot marks at the correct positions and you
// drill them to size. Position is knowable from first principles today.
// Diameter is not.
port_dia = undef;
